### ISSUE TITLE
i686 GCC 7.2 + glibc breaks C++ std::signbit

### ISSUE THREAD

**Issue by jktjkt** [free-electrons/toolchains-builder#7]
The [bleedging-edge toolchain with GCC 7.2 and glibc for i686](http://toolchains.free-electrons.com/downloads/releases/toolchains/x86-i686/tarballs/x86-i686--glibc--bleeding-edge-2017.08-rc2-5-g5c1b185-1.tar.bz2) has broken support for [std::signbit](http://en.cppreference.com/w/cpp/numeric/math/signbit):

```c++
#include <iostream>
#include <cmath>

int main()
{
    std::cout << std::boolalpha
              << "signbit(+0.0) = " << std::signbit(+0.0) << '\n'
              << "signbit(-0.0) = " << std::signbit(-0.0) << '\n';
}
```
```
 $ /home/jkt/work/prog/_build/br-geode/host/bin/i686-linux-g++ --sysroot=/home/jkt/work/prog/_build/br-geode/host/i686-buildroot-linux-gnu/sysroot -std=c++14 -o /dev/null -c foo.cpp 
In file included from /home/jkt/work/prog/_build/br-geode/host/opt/ext-toolchain/i686-buildroot-linux-gnu/include/c++/7.2.0/cmath:45:0,
                 from foo.cpp:2:
foo.cpp: In function ‘int main()’:
foo.cpp:7:45: error: ‘__builtin_signbit’ is not a member of ‘std’
               << "signbit(+0.0) = " << std::signbit(+0.0) << '\n'
                                             ^
foo.cpp:7:45: note: suggested alternative:
<built-in>: note:   ‘__builtin_signbit’
foo.cpp:8:45: error: ‘__builtin_signbit’ is not a member of ‘std’
               << "signbit(-0.0) = " << std::signbit(-0.0) << '\n';
                                             ^
foo.cpp:8:45: note: suggested alternative:
<built-in>: note:   ‘__builtin_signbit’
```
I know that the code works fine with native GCC 6.3.0 (Gentoo) as well as Linaro ARM 6.3.1 and also with GCC 6.3.x as produced by Buildroot itself.  An online test at godbolt.org shows that GCC 7.2 [appears to work](https://godbolt.org/g/7VT7KT), so I'm reporting this issue here.

**Comment by RomainNaour** [comment]
Hi,

This is issue come from the glibc 2.26 release.
There is several C++ regression when you use the release tarball to generate cross-toolchains. This is the case here with the bleeding-edge toolchain.

Bleeding-edge toolchains must be regenerated with several patches backported from the glibc 2.26 stable branch. See [1]

Can you try to generate an internal Buildroot toolchain with the current master ?

Thanks!
Romain Naour

[1] https://git.buildroot.net/buildroot/commit/?id=d6a4807f9473b4322e96b77169ffcd6d9cd84170

**Comment by tpetazzoni** [comment]
This issue is now fixed:

- The bleeding edge toolchains now use glibc 2.27
- The stable toolchains have been rebuilt with glibc 2.26 from git, which contains numerous fixes, including the one for this problem.
